apiVersion: apps/v1
kind: Deployment
metadata:
 name: node-web-app
spec:
 replicas: 2
 selector:
     matchLabels:
       app: node-web-app
 template:
   metadata:
     labels:
       app: node-web-app
   spec:     # pod spec                  
     containers:
     - name: node-web-app
       image: us.icr.io/cldstd33-ns/node-web-app:latest
       ports:
         - containerPort: 8080
       env:
         - name: APIKEY
           value: gB1u9agtVTSARIHHlTB9RnHRxF3es-70H9XcJUudegqY
         - name: URL
           value: https://api.us-south.assistant.watson.cloud.ibm.com/instances/5f7c5f35-f251-4b98-8547-f30b5343acab
         - name: ASSISTANT_ID
           value: 6a435749-34ae-419c-b39a-8b9026a49a7d
       imagePullPolicy: Always

